version: "3.9"
services:
  backend:
    container_name: csv-backend
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8000:80"
    environment:
      - BACKEND_REDIS_URL=redis://csv-redis/
      - BACKEND_RMQ_URL=amqp://backend:backend@csv-rabbitmq/
      - BACKEND_RMQ_EXCHANGE=Tasks
  executor:
    container_name: csv-executor
    build:
      context: ./
      dockerfile: Dockerfile.executor
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./data:/app/data:ro
    environment:
      - EXECUTOR_REDIS_URL=redis://csv-redis/
      - EXECUTOR_AWS_ID
      - EXECUTOR_AWS_SECRET
      - EXECUTOR_AWS_URL=https://storage.yandexcloud.net
      - EXECUTOR_RMQ_URL=amqp://executor:executor@csv-rabbitmq/
      - EXECUTOR_RMQ_QUEUE=tasks
  redis:
    container_name: csv-redis
    image: "redis:alpine"
  rabbitmq:
    container_name: csv-rabbitmq
    image: "rabbitmq:3.10.7-alpine"
    volumes:
      - ./rabbitconf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitconf/definitions.json:/etc/rabbitmq/definitions.json:ro
